device: "cuda"

dataset:
  name: "breastmnist"
  split_ratio: 0.8
  img_size: 28

training:
  model: resnet18
  batch_size: 64
  epochs: 10
  lr: 0.001
  optimizer: "adam"

logging:
  wandb_project: "chimac-benchmark"
  wandb_entity: "runs-nsut"
  log_interval: 10

system_monitor:
  interval_sec: 1