device: "cuda"

dataset:
  name: "pathmnist"
  split_ratio: 0.8
  img_size: 28

augmentation:
  k: 4.0
  alpha: 0.05
  seed: 42
  ops:
    [
      "op_brightness",
      "op_contrast",
      "op_flip",
      "op_hue",
      "op_rotate",
      "op_saturation",
      "op_scale",
      "op_translate",
    ]

training:
  model: resnet18
  batch_size: 64
  epochs: 100
  lr: 0.001
  optimizer: "adam"

logging:
  wandb_project: "chimac-benchmark"
  wandb_entity: "runs-nsut"
  log_interval: 10

system_monitor:
  interval_sec: 1
